### ISSUE TITLE
#urlbar opens downwards and so that's not good with the navbar at the bottom

### ISSUE THREAD

**Issue by madduck** [Arty2/userstyles#2]
I've been using CSS to move the tab bar to the bottom for years, and just merged it with your code, so now I can track your work better and we can work together ;)

There is one issue I cannot figure out, and while it sounds similar to #1, it's not. uBlock works for me, but the "urlbar" ("megabar") opens downwards.

I actually had this working at some point, and this was the code:

```
/* open URL bar to top */
#urlbar.megabar[breakout][breakout-extend]{
  display: flex !important;
  flex-direction: column-reverse;
  bottom: -2px !important; /* Change to 3-5 px if using compact_urlbar_megabar.css depending on toolbar density *//*
  top: auto !important;
}

#urlbar.megabar[open] > .urlbarView{ margin-block: 0px calc(var(--urlbar-height) + 1px) !important; box-shadow: none !important; }
```

but that no longer works. Do you have an idea why?

**Comment by Arty2** [comment]
Hi @madduck this has been fixed in the latest version. I think the key was to target `#urlbar.megabar[open]` instead.
