### ISSUE TITLE
tabs_to_bottom.userchrome.css moves the titlebar to bottom

### ISSUE THREAD

**Issue by Vosjedev** [Arty2/userstyles#4]
I enabled the menubar to have a window border at the top to still grab, but this also moves that. would it be possible to put the menubar back at the top?

![image](https://github.com/Arty2/userstyles/assets/100359465/543fae7c-2b29-49a4-9753-a4abeb9401c0)

**Comment by Arty2** [comment]
Not possible to easily modify this script unfortunately, the menu and tab
bar are coupled together.
However you should still be able to grab the window from the address bar
(left of the Pocket icon).

**Comment by lilly-lizard** [comment]
IMO I prefer having the address bar on the bottom too! most of the time I am focusing on the main webpage and only every now and then glance down to do address/tab bar stuff. also looks like its completely broken with 119.0 now anyway...
